### PR TITLE
fix: navigation selection highlight

### LINKED ISSUE #33: The Nav options is not highlighted on selected route
**Describe the bug**

The Navigation menu should be highlighted as per route selection.

**To Reproduce**

**Expected behavior**
Should highlight option based on selection

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
The issue is likely because both text-gray-200 and text-gray-400 classes are being applied simultaneously. This can happen if Angular's router doesn't recognize the exact match properly or if there is some CSS specificity issue.

### PR DESCRIPTION
**Pull request by yshashi**
## This PR Closes Issue

closes #33 

## Description
PR includes the following changes:
- Enhances the navigation active link styling
- Introduces a new Angular pipe for converting byte values to appropriate KB units

## What type of PR is this? (check all applicable)

- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Mobile & Desktop Screenshots/Recordings

[Attach screenshots or recordings if applicable]

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

## [Optional] Post-deployment tasks

[Specify any post-deployment tasks that need to be performed]

## [Optional] What gif best describes this PR or how it makes you feel?

[Embed gif or describe the feeling in plain text]

### CODE REVIEW

File: pdf/src/app/shared/components/header/header.component.ts [hunk 1]
```diff
@@ -19,6 +19,19 @@ import { LoginComponent, ProfileComponent } from '@pdfun/ui/auth'
     RouterLinkWithHref,
     RouterLinkActive,
   ],
+  styles: `
+  .link {
```
Comment (dalenguyen) [inline pdf/src/app/shared/components/header/header.component.ts:23]: Instead of having custom styling in the component. We can extend Tailwind functionality. 

https://tailwindcss.com/docs/theme#extending-the-default-theme

After that, we can use `link` class anywhere.

File: pdf/src/app/shared/pipes/bytes-to-kb.pipe.ts [hunk 2]
```diff
@@ -0,0 +1,14 @@
+import { Pipe, PipeTransform } from '@angular/core'
+
+@Pipe({
+  name: 'byteToKb',
+  standalone: true,
+})
+export class ByteToKbPipe implements PipeTransform {
+  transform(value: number): string {
```
Comment (dalenguyen) [inline pdf/src/app/shared/pipes/bytes-to-kb.pipe.ts:8]: Can we turn into more general pipe that take `kb, mb` as the parameter? 

`bytes | 'kb'` or `bytes | 'mb'` 

If it invalid, we can the original value.

File: pdf/src/app/pages/(home).page.ts [hunk 3]
```diff
@@ -13,6 +13,7 @@ import { ToastModule } from 'primeng/toast'
 import { DisclaimerComponent } from '../shared/components/disclaimer/disclaimer.component'
 import { PdfHandlerBase } from '../shared/components/pdf-handler-base/pdf-handler-base.directive'
 import { ShoutOutComponent } from '../shared/components/shout-out/shout-out.component'
+import { ByteToKbPipe } from '../shared/pipes/bytes-to-kb.pipe'
```
Comment (dalenguyen) [inline pdf/src/app/pages/(home).page.ts:16]: We can create an `index.ts` for shared pipes, then we can import like this 

```
import { ByteToKbPipe } from '../shared/pipes
```

File: pdf/src/app/shared/pipes/bytes-to-kb.pipe.ts (hunk 2 above)
Comment (yshashi) [reply pdf/src/app/shared/pipes/bytes-to-kb.pipe.ts:8]: How about making it dynamically check the unit? if it is bytes, kb, or MB
I will update the PR you can let me know if that's okay!

File: pdf/src/app/shared/components/header/header.component.ts (hunk 1 above)
Comment (yshashi) [reply pdf/src/app/shared/components/header/header.component.ts]: Added it as part of @layer component so that it can be reused

File: pdf/src/app/pages/(home).page.ts (hunk 3 above)
Comment (yshashi) [reply pdf/src/app/pages/(home).page.ts]: Done

File: pdf/src/app/shared/components/header/header.component.ts (hunk 1 above)
Comment (dalenguyen) [reply pdf/src/app/shared/components/header/header.component.ts]: That works!

File: pdf/src/app/shared/pipes/bytes-to-kb.pipe.ts (hunk 2 above)
Comment (dalenguyen) [reply pdf/src/app/shared/pipes/bytes-to-kb.pipe.ts]: Cool. That's ok!

**Review by dalenguyen — APPROVED** [review]
